{% set name = "thor" %}
{% set version = "1.0.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 7572061e3cbe6feee57828670e6a25a66dd397f05c1f8515d49f770a7d9d70f5

build:
  noarch: generic
  number: 1
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r zip -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple and efficient tool for building self-documenting command line utilities
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/erikhuda/{{ name }}

extra:
  recipe-maintainers:
    - sodre
    - Tata17
    - oblute
    - rluria14
